# Generated by Django 4.0.6 on 2022-07-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiares',
            old_name='date_of_birth',
            new_name='date',
        ),
    ]
